###

POST http://localhost:37471/odata/v4/srv/calculate
Content-Type: application/json

{
    "input": {
        "test":"test123"
    }
}

###


POST http://localhost:37471/rest/srv/calculate
Content-Type: application/json

{
    "input":{
        "test":"test123"
    }
}

####


POST http://localhost:46571/odata/v4/srv/student
Content-Type: application/json

{
    "name" : "Manish",
    "gender":  "M"
}


###

POST http://localhost:4004/odata/v4/ui/Incidents
Content-Type: application/json

{
    "location":"Pune",
    "incidentType":[
        {
            "master_ID":6
        }
    ],
    "employees":[{
        "name":"manish",
        "location":"pune"
    }],
    "witness":[
        {
            "name":"witness",
            "statement":"statement"
        }
    ]
}